version: '3'

services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: phpswoole/swoole
    volumes:
      - .:/rootfilesystem/
    working_dir: /var/www/html
